// The existing conversation design remains a prototype; PDF and narration use the independent reader.
const shapes={menu:'<path d="M4 6h16M4 12h16M4 18h10"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',book:'<path d="M12 5v15M12 5C8 2 4 3 3 4v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Z"/>',chevron:'<path d="m8 10 4 4 4-4"/>',mic:'<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M9 22h6"/>',send:'<path d="M12 19V5m-6 6 6-6 6 6"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h4"/>',save:'<path d="M6 3h12a1 1 0 0 1 1 1v17l-7-4-7 4V4a1 1 0 0 1 1-1Z"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',new:'<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7M17 3l4 4M9 15l1-5L18 2l4 4-8 8-5 1Z"/>',library:'<path d="M4 3v18M9 3v18M15 3l5 18M2 6h9M2 18h9"/>',notes:'<rect x="5" y="3" width="15" height="18" rx="2"/><path d="M3 7h4M3 12h4M3 17h4M11 8h5M11 12h5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',stop:'<rect x="5" y="5" width="14" height="14" rx="3"/>',min:'<path d="M4 8h4V4m12 12h-4v4M8 8 3 3m13 13 5 5"/>',expand:'<path d="M8 4H4v4m12 12h4v-4M4 4l5 5m11 11-5-5"/>',check:'<path d="m5 12 4 4L19 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h1M3 12h1M3 18h1"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',chat:'<path d="M21 12a9 9 0 0 1-9 9 10 10 0 0 1-4-1l-5 1 1-5a10 10 0 0 1-1-4 9 9 0 0 1 18 0Z"/>',battery:'<rect x="2" y="7" width="17" height="10" rx="2"/><path d="M22 10v4M5 10h11v4H5Z"/>',wifi:'<path d="M2 8a16 16 0 0 1 20 0M6 12a10 10 0 0 1 12 0m-8 4a3 3 0 0 1 4 0"/>',signal:'<path d="M4 19v-3M9 19v-7m5 7V8m5 11V4"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${shapes[n]||shapes.more}</svg>`;
const button=(n,label,action,cls='')=>`<button class="icon-button ${cls}" aria-label="${label}" title="${label}" data-action="${action}">${icon(n)}</button>`;
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const book='هنر یادگیری';
const passage='وقتی تلاش می‌کنیم مطلبی را از حافظه به یاد بیاوریم، یادگیری ماندگارتر می‌شود.';
const status=()=>`<div class="status"><span>۹:۴۱</span><span class="system-icons">${icon('signal')}${icon('wifi')}${icon('battery')}</span></div>`;
const topbar=reader=>`<div class="topbar">${button('menu',reader?'منوی کتاب‌خوان':'منوی چت','menu','menu-button')}<div><h3>${reader?book:'همراه'}</h3><p>${reader?'فصل دوم · صفحهٔ ۱۱':book}</p></div></div>`;
const actions=()=>`<div class="answer-actions">${button('copy','کپی پاسخ','copy')}${button('save','ذخیره در یادداشت','save')}${button('more','بیشتر','more')}</div>`;
const citation=()=>`<button class="cite-sent" data-action="citation">${passage}</button><button class="cite-pages" data-action="citation">${book} · صفحهٔ ۱۱</button>`;
const composer=()=>`<div class="chat-composer"><textarea rows="1" aria-label="پیام به همراه" placeholder="از همراه بپرسید…"></textarea><div class="composer-tools"><button class="pages-button" data-action="pages" aria-label="انتخاب صفحات زمینه؛ صفحهٔ ۱۱">${icon('book')}<span class="page-value">۱۱</span>${icon('chevron')}</button><div class="send-group">${button('mic','شروع ضبط گفتار','record')}${button('send','ارسال پیام','send-chat','send-button')}</div></div></div>`;
const conversation=()=>`<div class="conversation"><p class="date-label">امروز</p><div class="user-message">چرا یادآوری از دوباره‌خواندن بهتره؟</div><p class="message-context">${book} · صفحهٔ ۱۱</p><article class="assistant"><p>دوباره‌خواندن متن را آشنا می‌کند؛ یادآوری، حافظه را به کار می‌گیرد.</p><p>${citation()}</p><p>کتاب را ببندید و نکتهٔ اصلی را با زبان خودتان بگویید.</p>${actions()}<div class="study-card"><div class="study-head">${icon('book')}<span>${book} · صفحهٔ ۱۱</span></div><p>این بخش را دوباره ببینید و یک مثال برایش پیدا کنید.</p><button data-action="open-reader">بازکردن کتاب ${icon('book')}</button></div></article></div>`;
const navItem=(name,label,action,cls='')=>`<button class="nav-item ${cls}" data-action="${action}">${icon(name)}<span>${label}</span></button>`;
const historyItem=(title,current=false,bookName=book)=>`<div class="history-item ${current?'current':''}"><button class="history-name" data-action="history">${title}<small>${bookName}</small></button>${button('more','اقدام‌های گفتگو: '+title,'history-more')}</div>`;
const drawer=(reader,open=false)=>`<button class="drawer-scrim" aria-label="بستن منو با لمس بیرون" data-action="close-menu" ${open?'':'hidden'}></button><aside class="drawer" aria-label="${reader?'منوی کتاب‌خوان':'منوی چت'}" ${open?'':'hidden'}><div class="drawer-title"><span>${reader?'کتاب‌خوان':'گفتگوهای شما'}</span>${button('close','بستن منو','close-menu')}</div><nav class="drawer-nav">${reader?navItem('list','فهرست کتاب','deferred')+navItem('search','جستجو در کتاب','deferred')+navItem('book','رفتن به شمارهٔ صفحه','pdf-pages')+navItem('book','شنیدن کتاب','pdf-audio')+navItem('notes','دفتر یادداشت','notebook')+navItem('settings','تنظیمات مطالعه','pdf-pages')+navItem('chat','رفتن به چت','open-chat'):navItem('new','گفتگوی تازه','new-chat','new-chat')+navItem('book','کتاب‌خوان','open-reader')+navItem('library','انتخاب کتاب','books')+navItem('notes','دفتر یادداشت','notebook')}</nav>${reader?'<div class="history"></div>':`<div class="history"><p class="history-label">امروز</p>${historyItem('یادآوری یا دوباره‌خواندن؟',true)}${historyItem('برنامهٔ مطالعهٔ فصل دوم')}<p class="history-label">۷ روز گذشته</p>${historyItem('تمرین برای یادگیری ماندگار')}${historyItem('چطور عادت مطالعه بسازم؟',false,'عادت‌های کوچک')}<p class="history-label">قدیمی‌تر</p>${historyItem('از کجا شروع کنم؟')}</div>`}<button class="account-button" data-action="account"><span class="account-icon">${icon('user')}</span><span>حساب من<small>اشتراک فعال</small></span></button></aside>`;
const pagesSheet=()=>`<button class="sheet-scrim" data-action="close-sheet" aria-label="بستن انتخاب صفحه" hidden></button><section class="sheet" aria-label="انتخاب صفحات زمینه" hidden><div class="sheet-title"><h3>صفحات زمینهٔ پرسش</h3>${button('close','بستن پنل صفحات','close-sheet')}</div><p style="font-size:12px;color:var(--muted)">${book}</p><div class="single-input"><label>شمارهٔ صفحه</label><input class="single-page" value="۱۱" inputmode="numeric" aria-label="شمارهٔ صفحه"></div><label class="range-check"><input type="checkbox" class="range-toggle">انتخاب بازه</label><div class="range-inputs" hidden><div><label>از صفحه</label><input class="from-page" value="۱۱" inputmode="numeric" aria-label="از صفحه"></div><div><label>تا صفحه</label><input class="to-page" value="۱۵" inputmode="numeric" aria-label="تا صفحه"></div></div><p class="sheet-error" role="alert"></p><button class="primary-action" data-action="confirm-pages">تأیید</button><button class="clear-pages" data-action="clear-pages">حذف انتخاب صفحات</button></section>`;
const readerPage=()=>`<div class="reader-page" aria-label="صفحهٔ اصلی PDF"><div class="pdf-surface"><p class="pdf-placeholder" role="status">در حال بازکردن کتاب…</p></div></div>
<div class="reader-selection-actions" hidden><button data-action="ask-agent">${icon('chat')}پرسش از ایجنت</button></div>
<button class="sheet-scrim" data-pdf-dismiss aria-label="بستن ابزار مطالعه" hidden></button>
<section class="sheet pdf-page-sheet" aria-label="رفتن به صفحهٔ کتاب" hidden><div class="sheet-title"><h3>صفحهٔ کتاب</h3><button class="icon-button" data-pdf-dismiss aria-label="بستن ابزار مطالعه">${icon('close')}</button></div><form data-pdf-page-form><label>شمارهٔ صفحه<input name="page" inputmode="numeric" aria-label="شمارهٔ صفحهٔ کتاب" value="۱"></label><p data-pdf-page-count></p><p data-pdf-error role="alert"></p><button class="primary-action" type="submit">رفتن به صفحه</button></form><div class="pdf-pagination"><button data-pdf-prev>صفحهٔ پیش</button><button data-pdf-next>صفحهٔ بعد</button></div><div class="pdf-pagination"><button data-pdf-zoom="-0.25">کوچک‌نمایی</button><button data-pdf-zoom="0.25">بزرگ‌نمایی</button></div></section>
<section class="sheet pdf-audio-sheet" aria-label="شنیدن کتاب" hidden><div class="sheet-title"><h3>شنیدن کتاب</h3><button class="icon-button" data-pdf-dismiss aria-label="بستن ابزار مطالعه">${icon('close')}</button></div><button class="primary-action" data-reader-read disabled>شنیدن صفحه</button><div class="pdf-audio-buttons"><button data-reader-toggle disabled>پخش</button><button data-reader-stop disabled>توقف</button><select data-reader-speed aria-label="سرعت پخش"><option value="0.75">۰٫۷۵×</option><option value="1" selected>۱×</option><option value="1.25">۱٫۲۵×</option><option value="1.5">۱٫۵×</option><option value="2">۲×</option></select></div><input type="range" data-reader-seek min="0" max="0" step="0.1" value="0" disabled aria-label="زمان پخش"><p data-reader-audio-status role="status"></p><button data-pdf-clear-selection>حذف انتخاب متن</button></section>`;
const responseCard=()=>`<article class="response-card"><p><strong>یعنی خودِ تلاش برای یادآوری، بخشی از یادگیری است.</strong></p><p>مثلاً کتاب را ببندید و بگویید چه چیزی یاد گرفته‌اید. اگر جایی را فراموش کردید، همان بخش را دوباره ببینید.</p><p>${citation()}</p>${actions()}</article>`;
const inputBar=(draft='')=>`<div class="floating-bar"><div class="send-group">${button('mic','شروع ضبط گفتار در کتاب‌خوان','reader-record')}${button('send','ارسال پرسش در کتاب‌خوان','send-reader','send-button')}</div><div class="input-wrap"><input aria-label="پرسش از متن انتخاب‌شده" placeholder="دربارهٔ این متن بپرسید…" value="${esc(draft)}"></div></div>`;
const floating=(state,question=null)=>state==='idle'?'<div class="reader-floating" data-state="idle" hidden></div>':`<div class="reader-floating" data-state="${state}"><button class="restore-response" data-action="restore" hidden>${icon('chat')}بازکردن پاسخ</button>${question?`<div class="question-selection"><blockquote class="question-context">${esc(question.selection.text)}</blockquote>${button('close','بستن پرسش و بازگشت به مطالعه','close-question')}</div>`:''}${state==='response'?`<button class="minimise" data-action="minimise">${icon('min')}کوچک‌کردن</button>${responseCard()}`:''}${state==='loading'?`<button class="minimise" data-action="minimise">${icon('min')}کوچک‌کردن</button><div class="floating-bar">${button('stop','توقف پاسخ','stop-reader','stop-button')}<div class="loading-label"><span class="loading-dot"></span><span>در حال آماده‌کردن پاسخ…</span></div></div>`:inputBar(question?.draft||'')}</div>`;
const phone=(type,state)=>`<div class="phone" data-type="${type}" data-initial="${state}">${status()}${topbar(type==='reader')}${type==='reader'?readerPage()+floating(state):conversation()+composer()}${drawer(type==='reader',state==='menu')}${type==='chat'?pagesSheet():''}<div class="toast" role="status" hidden></div><div class="home-indicator"></div></div>`;
const unit=(label,detail,type,state)=>`<div class="screen-unit"><div class="screen-caption"><strong>${label}</strong><span>${detail}</span></div>${phone(type,state)}</div>`;
const view=new URLSearchParams(location.search).get('view')||'all';
document.querySelectorAll('.board-tools a').forEach(a=>{if(new URL(a.href).searchParams.get('view')===view)a.classList.add('active')});
document.querySelector('#boards').innerHTML=(view!=='reader'?`<section class="board-section"><div class="section-heading"><h2>گفتگو با همراه</h2><p>پاسخ در فضای باز؛ دسترسی کتاب‌خوان در منو</p></div><div class="screens">${unit('صفحهٔ چت','کنترل صفحهٔ ۱۱','chat','chat')}${unit('منوی چت','بازشده از راست','chat','menu')}</div></section>`:'')+(view!=='chat'?`<section class="board-section"><div class="section-heading"><h2>پرسش، داخل کتاب‌خوان</h2><p>ورودی پرسش فقط با انتخاب متن و زدن «پرسش از ایجنت» باز می‌شود</p></div><div class="screens">${unit('مطالعهٔ کتاب','حالت پیش‌فرض · بدون ورودی چت','reader','idle')}${unit('انتظار پاسخ','نمونهٔ پس از ارسال پرسش','reader','loading')}${unit('کارت پاسخ','نمونهٔ پس از دریافت پاسخ','reader','response')}</div></section>`:'');
const toast=(p,text)=>{const t=p.querySelector('.toast');t.textContent=text;t.hidden=false;clearTimeout(t.timer);t.timer=setTimeout(()=>t.hidden=true,2500)};
const closeMenu=p=>p.querySelectorAll('.drawer,.drawer-scrim').forEach(x=>x.hidden=true);
const setReader=(p,state)=>{const old=p.querySelector('.reader-floating');if(old)old.outerHTML=floating(state,p.readerQuestion)};
document.addEventListener('reader-question',e=>{const p=e.target.closest('.phone');if(!p)return;p.readerQuestion={selection:e.detail,draft:''};setReader(p,'ready');p.querySelector('.floating-bar input').focus({preventScroll:true});});
document.addEventListener('reader-question-reset',e=>{const p=e.target.closest('.phone');if(!p)return;p.readerQuestion=null;setReader(p,'idle');});
document.addEventListener('input',e=>{const p=e.target.closest('.phone');if(p?.readerQuestion&&e.target.matches('.floating-bar input'))p.readerQuestion.draft=e.target.value;});
const normalize=n=>Number(n.replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)));
const persian=n=>String(n).replace(/\d/g,c=>'۰۱۲۳۴۵۶۷۸۹'[c]);
document.querySelector('#theme-toggle').onclick=e=>{document.body.classList.toggle('dark');e.target.textContent=document.body.classList.contains('dark')?'نمای روشن':'نمای تیره'};
document.addEventListener('change',e=>{if(e.target.matches('.range-toggle')){const s=e.target.closest('.sheet');s.querySelector('.range-inputs').hidden=!e.target.checked;s.querySelector('.single-input').hidden=e.target.checked}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.phone').forEach(p=>{closeMenu(p);p.querySelectorAll('.sheet,.sheet-scrim').forEach(x=>x.hidden=true);if(p.readerQuestion)p.querySelector('[data-action="close-question"]')?.click()})});
document.addEventListener('click',async e=>{
 const target=e.target.closest('[data-action]');if(!target)return;const p=target.closest('.phone');const action=target.dataset.action;
 if(action==='menu')p.querySelectorAll('.drawer,.drawer-scrim').forEach(x=>x.hidden=false);
 if(action==='close-menu')closeMenu(p);
 if(action==='open-reader'||action==='citation'){closeMenu(p);if(p.dataset.type==='reader'){toast(p,'برای نقل‌قول واقعی، متن را از PDF انتخاب کنید.');return}p._chatDraft=p.querySelector('textarea').value;p._chatScroll=p.querySelector('.conversation').scrollTop;p._chatHtml=p.innerHTML;p.dataset.type='reader';p.innerHTML=p._readerHtml||(status()+topbar(true)+readerPage()+floating('idle')+drawer(true)+'<div class="toast" role="status" hidden></div><div class="home-indicator"></div>');if(p._readerDraft&&p.querySelector('.floating-bar input'))p.querySelector('.floating-bar input').value=p._readerDraft;toast(p,action==='citation'?'صفحهٔ ۱۱ · متن استناد در کتاب':'ادامهٔ مطالعه · صفحهٔ ۱۱');}
 if(action==='open-chat'){closeMenu(p);p._readerDraft=p.querySelector('.floating-bar input')?.value||'';p._readerHtml=p.innerHTML;p.dataset.type='chat';p.innerHTML=p._chatHtml||(status()+topbar(false)+conversation()+composer()+drawer(false)+pagesSheet()+'<div class="toast" role="status" hidden></div><div class="home-indicator"></div>');if(p._chatDraft)p.querySelector('textarea').value=p._chatDraft;if(p._chatScroll)p.querySelector('.conversation').scrollTop=p._chatScroll;}
 if(action==='pages')p.querySelectorAll('.sheet,.sheet-scrim').forEach(x=>x.hidden=false);
 if(action==='close-sheet')p.querySelectorAll('.sheet,.sheet-scrim').forEach(x=>x.hidden=true);
 if(action==='confirm-pages'||action==='clear-pages'){const s=p.querySelector('.sheet'),range=s.querySelector('.range-toggle').checked;const start=normalize(s.querySelector(range?'.from-page':'.single-page').value),end=range?normalize(s.querySelector('.to-page').value):start;if(action==='confirm-pages'&&(!Number.isInteger(start)||!Number.isInteger(end)||start<1||end<start)){s.querySelector('.sheet-error').textContent='شمارهٔ صفحه و ترتیب بازه را بررسی کنید.';return}const label=action==='clear-pages'?'انتخاب صفحه':start===end?persian(start):`${persian(start)}–${persian(end)}`;p.querySelector('.page-value').textContent=label;p.querySelector('.pages-button').setAttribute('aria-label','انتخاب صفحات زمینه؛ '+label);p.querySelectorAll('.sheet,.sheet-scrim').forEach(x=>x.hidden=true);s.querySelector('.sheet-error').textContent='';}
 if(action==='save'){target.innerHTML=icon('check');target.setAttribute('aria-label','ذخیره شد');toast(p,'ذخیره شد · نمایش نمونه')}
 if(action==='copy'){const text=target.closest('article').innerText;try{await navigator.clipboard.writeText(text);toast(p,'پاسخ کپی شد')}catch{toast(p,'کپی در این مرورگر در دسترس نیست')}}
 if(['account','notebook','books','history','history-more','more','deferred'].includes(action))toast(p,{account:'طرح حساب در مرحلهٔ بعد تکمیل می‌شود.',notebook:'طرح دفتر یادداشت در مرحلهٔ بعد تکمیل می‌شود.',books:'پنل انتخاب کتاب در طرح تکمیلی می‌آید.',history:'این ردیف، نمونهٔ فهرست گفتگوهاست.','history-more':'تغییر نام و حذف · پنجره‌ها در طرح تکمیلی',more:'جزئیات «بیشتر» هنوز در این طرح تعیین نشده.',deferred:'جزئیات این بخش برای دور کتاب‌خوان باقی مانده.'}[action]);
 if(action==='new-chat'){closeMenu(p);p.querySelector('.conversation').innerHTML='<article class="assistant" style="padding-top:130px"><h3>از کجای کتاب شروع کنیم؟</h3><p style="margin:12px 0 24px;font-size:15px">می‌توانید دربارهٔ کتاب بپرسید یا به مطالعه برگردید.</p><button class="nav-item" data-action="suggest-question">پرسیدن از کتاب</button><button class="nav-item" data-action="suggest-plan">برنامهٔ مطالعه</button><button class="nav-item" data-action="open-reader">بازگشت به مطالعه</button></article>'}
 if(action==='suggest-question'||action==='suggest-plan')p.querySelector('textarea').value=action==='suggest-question'?'این بخش از کتاب را توضیح بده.':'برای مطالعهٔ این کتاب یک برنامه پیشنهاد بده.';
 if(action==='send-chat'){const input=p.querySelector('textarea');if(!input.value.trim())return;const thread=p.querySelector('.conversation');const context=p.querySelector('.page-value').textContent;thread.insertAdjacentHTML('beforeend',`<div class="user-message">${esc(input.value)}</div><p class="message-context">${book}${context==='انتخاب صفحه'?'':' · صفحهٔ '+esc(context)}</p><article class="assistant"><p>این پاسخ صرفاً نمونهٔ پیش‌نمایش است؛ پرسشی به سرویس ارسال نمی‌شود.</p></article>`);input.value='';thread.scrollTop=thread.scrollHeight;}
 if(action==='send-reader'){const input=p.querySelector('.floating-bar input');if(!input?.value.trim())return;if(p.readerQuestion)p.readerQuestion.draft=input.value;setReader(p,'loading');}
 if(action==='close-question'){p.readerQuestion=null;setReader(p,'idle');}
 if(action==='stop-reader')setReader(p,'ready');
 if(action==='minimise'){const f=p.querySelector('.reader-floating');f.querySelector('.minimise').hidden=true;const r=f.querySelector('.response-card');if(r)r.hidden=true;const load=f.querySelector('.loading-label');if(load)load.textContent='در حال آماده‌کردن پاسخ…';f.querySelector('.restore-response').hidden=false;f.querySelector('.restore-response').dataset.restore=f.dataset.state;}
 if(action==='restore')setReader(p,target.dataset.restore||'response');
 if(action==='record'||action==='reader-record'){const c=p.querySelector(action==='record'?'.chat-composer':'.floating-bar');c.dataset.previous=c.innerHTML;c.innerHTML='<div class="recording"><span class="record-dot"></span><span>در حال ضبط · ۰۰:۰۳</span><button class="finish" data-action="finish-record">پایان</button><button class="cancel" data-action="cancel-record">لغو</button></div>';toast(p,'نمایش نمونهٔ ضبط؛ میکروفون روشن نمی‌شود.');}
 if(action==='finish-record'||action==='cancel-record'){const c=target.closest('.chat-composer,.floating-bar');c.innerHTML=c.dataset.previous;const input=c.querySelector('textarea,input');if(action==='finish-record')input.value='این بخش را با یک مثال توضیح بده.';}
});
